### ISSUE TITLE
Error handling backend / frontend

### ISSUE THREAD

**Issue by joberkel** [dribdat/dribdat#148]
1. Backend: Creating a new event and submitting an existing event title leads to webserver error and loss of all formdata.
2. Frontend: Following the "participants" link of an event fails with webserver error, if there aren't any submitted projects

**Comment by loleg** [comment]
@joberkel thanks for the ticket! 

1. Since we use plain old forms, if you click BACK in your browser, you shouldn't lose any data. But I totally see your point, and this is a super basic requirement of grown-up web apps. I think the issue is particularly painful if you're a participant and not an event organizer.

2. That is a relatively new feature and obviously was not tested enough. Thanks for raising! See #140
