### ISSUE TITLE
Broken links sometimes

### ISSUE THREAD

**Issue by gonzalocasas** [dribdat/dribdat#195]
I am not sure if I'm seeing double or something, but it seems there's an issue parsing some links. Check the video link on this project: http://now.makezurich.ch/project/66 
It fails to detect it as an absolute URL and tries to link it relative to the domain.

**Comment by gonzalocasas** [comment]
Seems like the question mark is what triggers this.

**Comment by loleg** [comment]
If you are talking about the YouTube video at the bottom, it seems to be working fine. The embedded slide presentation is not working because OneDrive/Powerpoint disallows IFRAME embedding. I don't know if this is a permission setting or the whole platform and would simply suggest an alternative like [SpeakerDeck](https://speakerdeck.com/).

Or maybe I am missing something here.. can you tell me specifically what link you think is the problem?

**Comment by gonzalocasas** [comment]
No, sorry, after reporting this, I started playing with the description and changed it for embedded which works. But it is not related. I just re-added the link as it was before (right below embedded video) and you can see what it does.

**Comment by loleg** [comment]
Thanks - fixed.

**Comment by loleg** [comment]
See also #182 and https://github.com/coleifer/micawber/issues/96
